name: ExtraPermissions
version: 2.1.0
main: io.github.soul4723.extrapermissions.ExtraPermissions
api-version: '1.20'
author: Soul4723
description: Granular permission control for vanilla Minecraft commands and features
website: https://github.com/Soul4723

depend: [CommandAPI, LuckPerms]

permissions:
  extrapermissions.use:
    description: Use ExtraPermissions commands
    default: op
  extrapermissions.reload:
    description: Reload ExtraPermissions configuration
    default: op
  extrapermissions.admin:
    description: Access ExtraPermissions admin features
    default: op
    
  # Command permissions
  minecraft.command.gamemode:
    description: Use /gamemode command
    default: false
  minecraft.command.gamemode.survival:
    description: Set gamemode to survival
    default: false
  minecraft.command.gamemode.creative:
    description: Set gamemode to creative
    default: false
  minecraft.command.gamemode.adventure:
    description: Set gamemode to adventure
    default: false
  minecraft.command.gamemode.spectator:
    description: Set gamemode to spectator
    default: false
  minecraft.command.gamemode.other:
    description: Change other players' gamemode
    default: false
  minecraft.command.gamemode.survival.other:
    description: Set other players to survival mode
    default: false
  minecraft.command.gamemode.creative.other:
    description: Set other players to creative mode
    default: false
  minecraft.command.gamemode.adventure.other:
    description: Set other players to adventure mode
    default: false
  minecraft.command.gamemode.spectator.other:
    description: Set other players to spectator mode
    default: false
  minecraft.command.teleport:
    description: Use /teleport command
    default: false
  minecraft.command.teleport.targets:
    description: Teleport self to entities/players
    default: false
  minecraft.command.teleport.location:
    description: Teleport self to coordinates
    default: false
  minecraft.command.teleport.targets.targets:
    description: Teleport entities to other entities
    default: false
  minecraft.command.teleport.targets.location:
    description: Teleport entities to coordinates
    default: false
    
  # Selector permissions
  minecraft.selector.entity.e:
    description: Use @e selector (all entities)
    default: false
  minecraft.selector.player.a:
    description: Use @a selector (all players)
    default: false
  minecraft.selector.player.p:
    description: Use @p selector (nearest player)
    default: false
  minecraft.selector.player.r:
    description: Use @r selector (random player)
    default: false
  minecraft.selector.self.s:
    description: Use @s selector (self)
    default: false
  minecraft.selector.player.effect.targets:
    description: Use player selectors in effect command
    default: false
  minecraft.selector.entity.effect.targets:
    description: Use entity selectors in effect command
    default: false
    
  # Whitelist command
  minecraft.command.whitelist:
    description: Use /whitelist command
    default: false
  minecraft.command.whitelist.add:
    description: Add player to whitelist
    default: false
  minecraft.command.whitelist.remove:
    description: Remove player from whitelist
    default: false
  minecraft.command.whitelist.on:
    description: Enable whitelist
    default: false
  minecraft.command.whitelist.off:
    description: Disable whitelist
    default: false

  # Time command
  minecraft.command.time:
    description: Use /time command
    default: false
  minecraft.command.time.set:
    description: Set world time
    default: false
  minecraft.command.time.add:
    description: Add time to world
    default: false
  minecraft.command.time.query:
    description: Query world time
    default: false

  # Effect command
  minecraft.command.effect:
    description: Use /effect command
    default: false
  minecraft.command.effect.give:
    description: Give effect to entity
    default: false
  minecraft.command.effect.clear:
    description: Clear effects from entity
    default: false

  # Weather command
  minecraft.command.weather:
    description: Use /weather command
    default: false
  minecraft.command.weather.clear:
    description: Clear weather
    default: false
  minecraft.command.weather.rain:
    description: Start rain
    default: false
  minecraft.command.weather.thunder:
    description: Start thunderstorm
    default: false

  # Gamerule command
  minecraft.command.gamerule:
    description: Use /gamerule command
    default: false
  minecraft.command.gamerule.query:
    description: Query gamerule value
    default: false
  minecraft.command.gamerule.set:
    description: Set gamerule value
    default: false

  # Difficulty command
  minecraft.command.difficulty:
    description: Use /difficulty command
    default: false
    
  # Bypass permissions
  minecraft.bypass.spawn-protection:
    description: Build inside spawn protection
    default: false
  minecraft.bypass.chat-speed:
    description: Bypass chat speed kick
    default: false
  minecraft.bypass.whitelist:
    description: Bypass server whitelist
    default: false
  minecraft.bypass.player-limit:
    description: Bypass server player limit
    default: false
  minecraft.bypass.force-gamemode:
    description: Override server force-gamemode setting
    default: false
  minecraft.bypass.move-speed.player:
    description: Bypass player movement speed kicks
    default: false
  minecraft.bypass.move-speed.vehicle.boat:
    description: Bypass movement speed kick while in boat
    default: false
  minecraft.bypass.move-speed.vehicle.minecart:
    description: Bypass movement speed kick while in minecart
    default: false
    
  # Admin permissions
  minecraft.adminbroadcast.receive:
    description: Receive command feedback
    default: false
  minecraft.debug_stick.use.block:
    description: Use debug stick on blocks
    default: false
  minecraft.operator_block.command_block.place:
    description: Place command blocks
    default: false
  minecraft.operator_block.command_block.view:
    description: View command block contents
    default: false
  minecraft.operator_block.command_block.break:
    description: Break command blocks
    default: false
  minecraft.operator_block.jigsaw.place:
    description: Place jigsaw blocks
    default: false
  minecraft.operator_block.jigsaw.view:
    description: View jigsaw blocks
    default: false
  minecraft.operator_block.jigsaw.break:
    description: Break jigsaw blocks
    default: false
  minecraft.operator_block.structure_block.place:
    description: Place structure blocks
    default: false
  minecraft.operator_block.structure_block.view:
    description: View structure blocks
    default: false
  minecraft.operator_block.structure_block.break:
    description: Break structure blocks
    default: false